# Generated by Django 4.0 on 2021-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default='Yes'),
        ),
    ]
